#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsSTJACPizvqwgifT4aZg/wgmlW4qG05GfGNAQlrv63LaX7j4QNVFbVEF6tIK2iQUnq/if4q2zvS12Ev/72brENcbQLfAkO0vvA2erGcVTPfKbnZDeoQdfD/FgtCZYlFkU2PMoF7DImFxFz4ru6drKkUefARfI5z2RQlPs61b/xlWXCV506+u2x8/A6/W+JqH/FqLDfMyEpA+H2fyYuE5mcwwxVQ3fjYkukCGQ2nbP8FSc2mB2PxzYDL0Egr3oP1YnPem1ErEwD8/4VB2JyyC+QmDhQAjCmG0evApZwLHulh2nQA/k93yj0M+Tk4zc3D2iWEy6uHgA79mGoMQ2S1Yt vagrant
